// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw_2gpp5q9iunnkrEA1vrC7v3Cg6xfq5w',
    appId: '1:848695406274:web:3298d2824f43edf2f0d55b',
    messagingSenderId: '848695406274',
    projectId: 'feelscore-df565',
    authDomain: 'feelscore-df565.firebaseapp.com',
    storageBucket: 'feelscore-df565.firebasestorage.app',
    measurementId: 'G-Y4XMLMTX48',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxXJPBq-uXaMBqwFFqCe4Oxg05kOVmPxI',
    appId: '1:848695406274:android:632a4017a571eaa7f0d55b',
    messagingSenderId: '848695406274',
    projectId: 'feelscore-df565',
    storageBucket: 'feelscore-df565.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpSoHAkEyMauEZtfe3ax2VPtpOk-YU3Zk',
    appId: '1:848695406274:ios:9ef4b10d67230d4df0d55b',
    messagingSenderId: '848695406274',
    projectId: 'feelscore-df565',
    storageBucket: 'feelscore-df565.firebasestorage.app',
    iosBundleId: 'com.example.frontapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpSoHAkEyMauEZtfe3ax2VPtpOk-YU3Zk',
    appId: '1:848695406274:ios:9ef4b10d67230d4df0d55b',
    messagingSenderId: '848695406274',
    projectId: 'feelscore-df565',
    storageBucket: 'feelscore-df565.firebasestorage.app',
    iosBundleId: 'com.example.frontapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCw_2gpp5q9iunnkrEA1vrC7v3Cg6xfq5w',
    appId: '1:848695406274:web:be9eb0f70e86679df0d55b',
    messagingSenderId: '848695406274',
    projectId: 'feelscore-df565',
    authDomain: 'feelscore-df565.firebaseapp.com',
    storageBucket: 'feelscore-df565.firebasestorage.app',
    measurementId: 'G-SLXD7FCRSP',
  );
}
